import { useEffect, useId, useRef, useState, type DragEvent, type KeyboardEvent } from 'react';

import type { LectureSourceDocumentKind } from './lecture-source-editor';
import { lectureSourceDocumentLabel } from './lecture-source-editor';
import './lecture-figure-library.css';

export type LectureFigureOrigin = 'user' | 'generated';

export type LectureFigureAssetView = Readonly<{
  id: string;
  thumbnailDataUrl: string;
  displayName: string;
  width: number;
  height: number;
  origin: LectureFigureOrigin;
  usedIn: readonly LectureSourceDocumentKind[];
  referenceCount?: number;
  caption?: string;
  altText?: string;
}>;

export type LectureFigureFileRejectionReason = 'empty-file' | 'unsupported-format';

export type LectureFigureFileRejection = Readonly<{
  fileName: string;
  reason: LectureFigureFileRejectionReason;
}>;

export type LectureFigureFilePartition = Readonly<{
  accepted: readonly File[];
  rejected: readonly LectureFigureFileRejection[];
}>;

export type LectureFigureLibraryProps = Readonly<{
  figures: readonly LectureFigureAssetView[];
  activeDocument: LectureSourceDocumentKind;
  onChooseFiles: () => void | Promise<void>;
  onDropFiles: (files: readonly File[]) => void | Promise<void>;
  onPreview: (figure: LectureFigureAssetView) => void;
  onInsert?: (figure: LectureFigureAssetView, document: LectureSourceDocumentKind) => void;
  onRemove: (figure: LectureFigureAssetView) => void;
  onRejectedFiles?: (rejections: readonly LectureFigureFileRejection[]) => void;
  disabled?: boolean;
  adding?: boolean;
  busyFigureId?: string | null;
  statusMessage?: string | null;
  errorMessage?: string | null;
  idPrefix?: string;
  previewFigure?: LectureFigureAssetView | null;
  onClosePreview?: () => void;
  canInsert?: boolean;
}>;

const LECTURE_FIGURE_MIME_TYPES = new Set([
  'image/png',
  'image/jpeg',
  'image/webp',
  'image/gif',
  'image/tiff',
  'image/bmp',
  'image/avif',
]);

const LECTURE_FIGURE_EXTENSIONS = new Set([
  'png',
  'jpg',
  'jpeg',
  'webp',
  'gif',
  'tif',
  'tiff',
  'bmp',
  'avif',
]);

const LECTURE_FIGURE_FILE_ACCEPT =
  '.png,.jpg,.jpeg,.webp,.gif,.tif,.tiff,.bmp,.avif,image/png,image/jpeg,image/webp,image/gif,image/tiff,image/bmp,image/avif';

function fileExtension(name: string) {
  const index = name.lastIndexOf('.');
  return index < 0 ? '' : name.slice(index + 1).toLocaleLowerCase();
}

export function isAcceptedLectureFigureFile(file: Pick<File, 'name' | 'type' | 'size'>) {
  if (file.size < 1) return false;
  if (LECTURE_FIGURE_MIME_TYPES.has(file.type.toLocaleLowerCase())) return true;
  return (
    (file.type === '' || file.type === 'application/octet-stream') &&
    LECTURE_FIGURE_EXTENSIONS.has(fileExtension(file.name))
  );
}

export function partitionLectureFigureFiles(files: readonly File[]): LectureFigureFilePartition {
  const accepted: File[] = [];
  const rejected: LectureFigureFileRejection[] = [];
  for (const file of files) {
    if (file.size < 1) {
      rejected.push({ fileName: file.name, reason: 'empty-file' });
    } else if (!isAcceptedLectureFigureFile(file)) {
      rejected.push({ fileName: file.name, reason: 'unsupported-format' });
    } else {
      accepted.push(file);
    }
  }
  return { accepted, rejected };
}

export function isLectureFigureFileDrag(types: ArrayLike<string>) {
  return Array.from(types).includes('Files');
}

export function lectureFigureUsageLabel(figure: LectureFigureAssetView) {
  const documents = new Set(figure.usedIn);
  if (documents.has('lecture-notes') && documents.has('slides')) return 'Used in Notes & Slides';
  if (documents.has('lecture-notes')) return 'Used in Notes';
  if (documents.has('slides')) return 'Used in Slides';
  return 'Unused';
}

export function lectureFigureOriginLabel(origin: LectureFigureOrigin) {
  return origin === 'generated' ? 'Generated by GOSU' : 'Added by you';
}

export function LectureFigureLibrary({
  figures,
  activeDocument,
  onChooseFiles,
  onDropFiles,
  onPreview,
  onInsert,
  onRemove,
  onRejectedFiles,
  disabled = false,
  adding = false,
  busyFigureId = null,
  statusMessage = null,
  errorMessage = null,
  idPrefix,
  previewFigure = null,
  onClosePreview,
  canInsert = onInsert !== undefined,
}: LectureFigureLibraryProps) {
  const generatedId = useId();
  const prefix = idPrefix ?? `lecture-figures-${generatedId.replaceAll(':', '')}`;
  const dragDepth = useRef(0);
  const previewReturnFocus = useRef<HTMLElement | null>(null);
  const previewWasOpen = useRef(false);
  const [dropActive, setDropActive] = useState(false);
  const statusId = `${prefix}-status`;
  const activeDocumentLabel = lectureSourceDocumentLabel(activeDocument);
  const unavailable = disabled || adding;

  useEffect(() => {
    if (previewFigure) {
      previewWasOpen.current = true;
      return;
    }
    if (!previewWasOpen.current) return;
    previewWasOpen.current = false;
    const returnTarget = previewReturnFocus.current;
    previewReturnFocus.current = null;
    const frame = requestAnimationFrame(() => returnTarget?.focus());
    return () => cancelAnimationFrame(frame);
  }, [previewFigure]);

  const requestPreview = (figure: LectureFigureAssetView) => {
    if (document.activeElement instanceof HTMLElement) {
      previewReturnFocus.current = document.activeElement;
    }
    onPreview(figure);
  };

  const addFiles = (files: readonly File[]) => {
    const partition = partitionLectureFigureFiles(files);
    if (partition.rejected.length > 0) onRejectedFiles?.(partition.rejected);
    if (partition.accepted.length > 0) void onDropFiles(partition.accepted);
  };

  const onDragEnter = (event: DragEvent<HTMLElement>) => {
    if (!isLectureFigureFileDrag(event.dataTransfer.types)) return;
    event.preventDefault();
    dragDepth.current += 1;
    if (!unavailable) setDropActive(true);
  };

  const onDragLeave = (event: DragEvent<HTMLElement>) => {
    if (!isLectureFigureFileDrag(event.dataTransfer.types)) return;
    event.preventDefault();
    dragDepth.current = Math.max(0, dragDepth.current - 1);
    if (dragDepth.current === 0) setDropActive(false);
  };

  const onDragOver = (event: DragEvent<HTMLElement>) => {
    if (!isLectureFigureFileDrag(event.dataTransfer.types)) return;
    event.preventDefault();
    event.dataTransfer.dropEffect = unavailable ? 'none' : 'copy';
  };

  const onDrop = (event: DragEvent<HTMLElement>) => {
    if (!isLectureFigureFileDrag(event.dataTransfer.types)) return;
    event.preventDefault();
    dragDepth.current = 0;
    setDropActive(false);
    if (!unavailable) addFiles(Array.from(event.dataTransfer.files));
  };

  return (
    <section
      className={`lecture-figure-library${dropActive ? ' drop-active' : ''}`}
      aria-labelledby={`${prefix}-heading`}
      aria-describedby={statusId}
      onDragEnter={onDragEnter}
      onDragLeave={onDragLeave}
      onDragOver={onDragOver}
      onDrop={onDrop}
    >
      <header className="lecture-figure-library-header">
        <div>
          <span className="eyebrow">Figure library</span>
          <h3 id={`${prefix}-heading`}>Figures ({figures.length})</h3>
          <p>
            {canInsert
              ? 'Drop images from Finder here, then preview or insert them at the cursor.'
              : 'Drop images from Finder here to make them available for the first generation.'}
          </p>
        </div>
        <button
          type="button"
          className="secondary-button"
          disabled={unavailable}
          onClick={() => void onChooseFiles()}
          aria-label="Choose lecture figure images"
          title={`Supported formats: ${LECTURE_FIGURE_FILE_ACCEPT}`}
        >
          {adding ? 'Adding…' : 'Add images'}
        </button>
      </header>

      {errorMessage && (
        <div className="lecture-figure-library-error" role="alert">
          <strong>Figure action did not complete</strong>
          <span>{errorMessage}</span>
        </div>
      )}

      <div className="lecture-figure-library-drop-copy">
        <strong>Finder drop zone</strong>
        <span>PNG, JPEG, WebP, GIF, TIFF, BMP, or AVIF</span>
      </div>

      {figures.length === 0 ? (
        <div className="lecture-figure-library-empty">
          <strong>No figures attached yet</strong>
          <span>Add images without leaving GOSU.</span>
        </div>
      ) : (
        <div className="lecture-figure-library-grid" role="list" aria-label="Lecture figures">
          {figures.map((figure) => {
            const busy = busyFigureId === figure.id;
            const usage = lectureFigureUsageLabel(figure);
            return (
              <article
                className="lecture-figure-card"
                role="listitem"
                aria-label={`${figure.displayName}, ${usage}`}
                key={figure.id}
              >
                <button
                  type="button"
                  className="lecture-figure-thumbnail"
                  disabled={disabled || busy}
                  onClick={() => requestPreview(figure)}
                  aria-label={`Preview ${figure.displayName}`}
                >
                  <img src={figure.thumbnailDataUrl} alt="" aria-hidden="true" />
                </button>
                <div className="lecture-figure-card-copy">
                  <strong title={figure.displayName}>{figure.displayName}</strong>
                  <small>
                    {figure.width.toLocaleString()} × {figure.height.toLocaleString()}
                  </small>
                  <div>
                    <span>{lectureFigureOriginLabel(figure.origin)}</span>
                    <span>{usage}</span>
                    {figure.referenceCount !== undefined && figure.referenceCount > 0 && (
                      <span>
                        {figure.referenceCount} reference{figure.referenceCount === 1 ? '' : 's'}
                      </span>
                    )}
                  </div>
                </div>
                <div className="lecture-figure-card-actions">
                  <button
                    type="button"
                    className="ghost-button"
                    disabled={disabled || busy}
                    onClick={() => requestPreview(figure)}
                    aria-label={`Preview ${figure.displayName}`}
                  >
                    Preview
                  </button>
                  {canInsert && onInsert && (
                    <button
                      type="button"
                      className="primary-button"
                      disabled={disabled || busy}
                      onClick={() => onInsert(figure, activeDocument)}
                      aria-label={`Insert ${figure.displayName} in ${activeDocumentLabel}`}
                    >
                      Insert at cursor
                    </button>
                  )}
                  <button
                    type="button"
                    className="ghost-button lecture-figure-remove"
                    disabled={disabled || busy}
                    onClick={() => onRemove(figure)}
                    aria-label={`Remove ${figure.displayName} from this Studio`}
                  >
                    Remove
                  </button>
                </div>
              </article>
            );
          })}
        </div>
      )}

      <div className="lecture-figure-library-status" id={statusId} role="status" aria-live="polite">
        {statusMessage ??
          (canInsert
            ? `${figures.length} figure${figures.length === 1 ? '' : 's'} available. Insertions target ${activeDocumentLabel}.`
            : `${figures.length} figure${figures.length === 1 ? '' : 's'} ready for the first generation.`)}
      </div>

      {dropActive && (
        <div className="lecture-figure-drop-overlay" role="status" aria-live="assertive">
          <strong>Release to add images</strong>
          <span>Files stay local until the parent revision workflow accepts them.</span>
        </div>
      )}
      {previewFigure && onClosePreview && (
        <LectureFigurePreviewDialog
          figure={previewFigure}
          headingId={`${prefix}-preview-heading`}
          onClose={onClosePreview}
        />
      )}
    </section>
  );
}

export function LectureFigurePreviewDialog({
  figure,
  headingId = 'lecture-figure-preview-heading',
  onClose,
}: Readonly<{ figure: LectureFigureAssetView; headingId?: string; onClose: () => void }>) {
  const closeButton = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    closeButton.current?.focus();
  }, [figure.id]);

  const keyDown = (event: KeyboardEvent<HTMLDivElement>) => {
    if (event.key === 'Escape') {
      event.preventDefault();
      onClose();
      return;
    }
    if (event.key === 'Tab') {
      event.preventDefault();
      closeButton.current?.focus();
    }
  };

  return (
    <div
      className="lecture-figure-preview-backdrop"
      role="presentation"
      onMouseDown={(event) => {
        if (event.target === event.currentTarget) onClose();
      }}
      onKeyDown={keyDown}
    >
      <section
        className="lecture-figure-preview-dialog"
        role="dialog"
        aria-modal="true"
        aria-labelledby={headingId}
      >
        <header>
          <div>
            <span className="eyebrow">Figure preview</span>
            <h3 id={headingId}>{figure.displayName}</h3>
          </div>
          <button
            type="button"
            className="ghost-button"
            ref={closeButton}
            onClick={onClose}
            aria-label={`Close preview of ${figure.displayName}`}
          >
            Close
          </button>
        </header>
        <div className="lecture-figure-preview-image">
          <img src={figure.thumbnailDataUrl} alt={figure.altText ?? figure.displayName} />
        </div>
        <footer>
          <span>
            {figure.width.toLocaleString()} × {figure.height.toLocaleString()}
          </span>
          <span>{lectureFigureOriginLabel(figure.origin)}</span>
          {figure.caption && <span>{figure.caption}</span>}
        </footer>
      </section>
    </div>
  );
}
