version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary

  - package-ecosystem: gomod
    directory: /apps/runner
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Seoul
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Seoul
    open-pull-requests-limit: 3
