packages:
  - apps/*
  - packages/*

overrides:
  find-my-way: 9.7.0
  postcss: 8.5.25
  sharp: 0.35.3

allowBuilds:
  better-sqlite3-multiple-ciphers: true
  electron: true
  electron-winstaller: false
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - globals@17.9.0
