import residualGradientEvidenceJson from './generated/residual-gradient-evidence.json';
import transformerFilmGradientEvidenceJson from './generated/transformer-film-gradient-evidence.json';
import { modelFormulaConsistencyFindings } from './model-formula-consistency';
import type {
  GradientObservationState,
  GradientTrace,
  ModelConnection,
  ModelGradientEvidence,
  ModelModule,
  ModelSpec,
  ObservedGradientScenario,
} from './model-lab-schema';

const checkpoints = [1, 2, 3, 4, 5] as const;
export const residualGradientEvidence =
  residualGradientEvidenceJson as unknown as ModelGradientEvidence;
export const transformerFilmGradientEvidence =
  transformerFilmGradientEvidenceJson as unknown as ModelGradientEvidence;

function syntheticTrace(values: readonly number[]): GradientTrace {
  const observed = values.map(() => 'observed' as const);
  const notObserved = values.map(() => 'not-observed' as const);
  return {
    checkpoints,
    healthy: values,
    vanishing: values.map((value, index) => value * Math.pow(0.055, 4 - index)),
    detached: values.map(() => Number.NaN),
    exploding: values.map((value, index) => value * Math.pow(7.8, index + 1)),
    states: {
      healthy: notObserved,
      vanishing: observed,
      detached: notObserved,
      exploding: observed,
    },
    scenarioKinds: {
      healthy: 'design-only',
      vanishing: 'synthetic-stress',
      detached: 'design-only',
      exploding: 'synthetic-stress',
    },
    scenarioLabels: {
      healthy: 'No backward execution has been observed for this design-only model',
      vanishing: 'Synthetic vanishing-gradient stress scenario',
      detached: 'No detached execution has been observed for this design-only model',
      exploding: 'Synthetic exploding-gradient stress scenario',
    },
  };
}

function observedScenarioEdge(scenario: ObservedGradientScenario, edgeId: string) {
  const edge = scenario.edges[edgeId];
  if (!edge) {
    throw new Error(`Generated gradient evidence is missing edge ${edgeId}.`);
  }
  return edge;
}

function numericGradients(values: readonly (number | null)[]): readonly number[] {
  return values.map((value) => value ?? Number.NaN);
}

function observedTrace(evidence: ModelGradientEvidence, edgeId: string): GradientTrace {
  const healthyScenario = evidence.scenarios.healthy;
  const detachedScenario = evidence.scenarios.detached;
  const healthyEdge = observedScenarioEdge(healthyScenario, edgeId);
  const detachedEdge = observedScenarioEdge(detachedScenario, edgeId);
  const healthy = numericGradients(healthyEdge.gradientRms);
  const syntheticStates = healthyEdge.states.map((state) =>
    state === 'observed' ? ('observed' as GradientObservationState) : state,
  );
  return {
    checkpoints: Array.from({ length: evidence.probeCount }, (_, index) => index + 1),
    healthy,
    vanishing: healthy.map((value, index) => value * Math.pow(0.055, 4 - index)),
    detached: numericGradients(detachedEdge.gradientRms),
    exploding: healthy.map((value, index) => value * Math.pow(7.8, index + 1)),
    states: {
      healthy: healthyEdge.states,
      vanishing: syntheticStates,
      detached: detachedEdge.states,
      exploding: syntheticStates,
    },
    scenarioKinds: {
      healthy: healthyScenario.kind,
      vanishing: 'synthetic-stress',
      detached: detachedScenario.kind,
      exploding: 'synthetic-stress',
    },
    scenarioLabels: {
      healthy: healthyScenario.label,
      vanishing: 'Synthetic stress transform of the observed healthy trace',
      detached: detachedScenario.label,
      exploding: 'Synthetic stress transform of the observed healthy trace',
    },
  };
}

function module(
  value: Omit<ModelModule, 'codeReference'> & Readonly<{ codeReference?: string }>,
): ModelModule {
  return {
    ...value,
    codeReference: value.codeReference ?? `model.py:${14 + value.stage * 7}`,
  };
}

function connection(
  value: Omit<ModelConnection, 'gradient' | 'expectedToCarryGradient'> &
    Readonly<{ gradient: readonly number[]; expectedToCarryGradient?: boolean }>,
): ModelConnection {
  return {
    ...value,
    gradient: syntheticTrace(value.gradient),
    expectedToCarryGradient: value.expectedToCarryGradient ?? true,
  };
}

function observedConnection(
  evidence: ModelGradientEvidence,
  value: Omit<ModelConnection, 'activationNorm' | 'gradient' | 'expectedToCarryGradient'> &
    Readonly<{ expectedToCarryGradient?: boolean }>,
): ModelConnection {
  const edge = observedScenarioEdge(evidence.scenarios.healthy, value.id);
  const activationNorm =
    edge.activationRms.reduce((sum, activation) => sum + activation, 0) / edge.activationRms.length;
  return {
    ...value,
    activationNorm,
    gradient: observedTrace(evidence, value.id),
    expectedToCarryGradient: value.expectedToCarryGradient ?? true,
  };
}

function notApplicableTrace(label: string): GradientTrace {
  const unavailable = checkpoints.map(() => Number.NaN);
  const notApplicable = checkpoints.map(() => 'not-applicable' as const);
  return {
    checkpoints,
    healthy: unavailable,
    vanishing: unavailable,
    detached: unavailable,
    exploding: unavailable,
    states: {
      healthy: notApplicable,
      vanishing: notApplicable,
      detached: notApplicable,
      exploding: notApplicable,
    },
    scenarioKinds: {
      healthy: 'design-only',
      vanishing: 'design-only',
      detached: 'design-only',
      exploding: 'design-only',
    },
    scenarioLabels: {
      healthy: label,
      vanishing: label,
      detached: label,
      exploding: label,
    },
  };
}

function compilerConnection(
  value: Omit<ModelConnection, 'activationNorm' | 'gradient' | 'expectedToCarryGradient'>,
): ModelConnection {
  return {
    ...value,
    activationNorm: Number.NaN,
    gradient: notApplicableTrace(
      'TROPIC is invoked under torch.no_grad(); this compiler boundary has no autograd signal.',
    ),
    expectedToCarryGradient: false,
  };
}

function structuralTrace(label: string): GradientTrace {
  const unavailable = checkpoints.map(() => Number.NaN);
  const notObserved = checkpoints.map(() => 'not-observed' as const);
  return {
    checkpoints,
    healthy: unavailable,
    vanishing: unavailable,
    detached: unavailable,
    exploding: unavailable,
    states: {
      healthy: notObserved,
      vanishing: notObserved,
      detached: notObserved,
      exploding: notObserved,
    },
    scenarioKinds: {
      healthy: 'design-only',
      vanishing: 'design-only',
      detached: 'design-only',
      exploding: 'design-only',
    },
    scenarioLabels: {
      healthy: label,
      vanishing: label,
      detached: label,
      exploding: label,
    },
  };
}

function structuralConnection(
  value: Omit<ModelConnection, 'activationNorm' | 'gradient' | 'expectedToCarryGradient'>,
): ModelConnection {
  return {
    ...value,
    activationNorm: Number.NaN,
    gradient: structuralTrace(
      'SPARKVSK has a differentiable standalone path, but this static reconstruction has no captured tensor-gradient receipt; TROPIC inference wraps it in torch.no_grad().',
    ),
    expectedToCarryGradient: true,
  };
}

export const sparkvskLearnedWarmPath: ModelSpec = {
  schemaVersion: 1,
  id: 'sparkvsk-learned-warm-path-20260822',
  name: 'SPARKVSK learned warm path',
  version: '2026-08-22 · nested static reconstruction',
  framework: 'PyTorch',
  sourceLabel: 'attached SPARK / SPARKVS / SPARKVSK sources · statically inspected',
  sourceArtifacts: [
    { path: 'TROPIC_PORTABLE_20260822/model_spark.py', verified: true },
    { path: 'TROPIC_PORTABLE_20260822/model_spark_vs.py', verified: true },
    { path: 'TROPIC_PORTABLE_20260822/model_spark_vs_k.py', verified: true },
    { path: 'TROPIC_PORTABLE_20260822/run_tropic.py', verified: true },
    { path: 'TROPIC_PORTABLE_20260822/README.md', verified: true },
  ],
  summary:
    'A λ-conditioned neural warm-start path: Krylov ridge summaries and bipartite feature/row embeddings are fused with a learned penalty-and-λ query, converted to diagonal scales, and solved by implicit PCG.',
  intent: {
    statement:
      'Predict one warm coefficient vector for every regularization level without constructing a full p × p system.',
    invariants: [
      'λ is an explicit path input: λq = lambda_ratioq × lambda_max before query construction.',
      'The penalty derivative is encoded jointly with log λ ratio, log λ, response scale, and log λmax.',
      'Four default bipartite blocks exchange messages Xᵀr/n and Xc/√p between coordinate and row latents.',
      'The learned head corrects an LQA-derived base log diagonal scale; the final solve uses implicit PCG with K = 48 by default.',
      'The README reports approximately 2.39M checkpoint parameters, but the checkpoint was not deserialized, so per-module parameter allocation is not claimed.',
    ],
    expectedInput: ['B', 'n', 'p'],
    expectedOutput: ['B', 'Q', 'p'],
  },
  modules: [
    module({
      id: 'sparkvsk-task',
      name: 'Regression batch + λ path',
      kind: 'input',
      group: 'Inputs',
      stage: 0,
      lane: 0,
      inputShape: ['B', 'n', 'p'],
      outputShape: ['B', 'n', 'p'],
      transform: 'bind X, y, λ ratio1:Q, λmax, penalty derivative ρ′ and penalty grid',
      activation: null,
      formula: String.raw`\mathcal I=(X,y,r_{1:Q},\lambda_{\max},\rho',\mathcal G)`,
      explanation:
        'X is the primary displayed tensor. y, the Q λ ratios, λmax, penalty derivative and grid enter as named side inputs used by the downstream feature and query branches.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/run_tropic.py:61-69',
    }),
    module({
      id: 'sparkvsk-standardize',
      name: 'Feature / response standardization',
      kind: 'normalization',
      group: 'Preprocessing',
      stage: 1,
      lane: 0,
      inputShape: ['B', 'n', 'p'],
      outputShape: ['B', 'n', 'p'],
      transform: 'center and scale each feature and response within batch',
      activation: null,
      formula: String.raw`X_{bij}\leftarrow\frac{X_{bij}-\mu_{X,bj}}{s_{X,bj}},\qquad y_{bi}\leftarrow\frac{y_{bi}-\mu_{y,b}}{s_{y,b}}`,
      explanation:
        'Stores feature scales sX and response statistics (μy, sy), which are later used to normalize λ and return coefficients to original units.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/model_spark.py:123-132',
    }),
    module({
      id: 'sparkvsk-krylov-features',
      name: 'Lanczos ridge feature banks',
      kind: 'linear',
      group: 'Krylov front-end',
      stage: 2,
      lane: 0,
      inputShape: ['B', 'n', 'p'],
      outputShape: ['B', 'p', 'F_c'],
      transform: 'R ≤ 32 Lanczos basis → 4 ridge solves → coordinate, row and global statistics',
      activation: 'clamp / log feature transforms',
      formula: String.raw`T=U^{\top}\!\left(XX^{\top}/p\right)U,\quad \alpha_k=U(T+\gamma_k I)^{-1}U^{\top}y,\quad \beta_k=X^{\top}\alpha_k/p`,
      explanation:
        'Builds cfeat for each coordinate plus rfeat, tfeat and gfeat side banks. It replaces the exact ridge feature construction with a response-seeded Lanczos subspace.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/model_spark_vs_k.py:17-89',
    }),
    module({
      id: 'sparkvsk-embeddings',
      name: 'Coordinate / row embeddings',
      kind: 'linear',
      group: 'Learned trunk',
      stage: 3,
      lane: 0,
      inputShape: ['B', 'p', 'F_c'],
      outputShape: ['B', 'p', 'd'],
      transform: 'emb_c and emb_r MLPs combine local feature banks with broadcast global features',
      activation: 'GELU',
      formula: String.raw`c_j=\operatorname{MLP}^{\mathrm{GELU}}_c([cfeat_j;g]),\qquad r_i=\operatorname{MLP}^{\mathrm{GELU}}_r([rfeat_i;g])`,
      explanation:
        'Creates d=64 coordinate latents c and row latents r. The graph follows c as the primary tensor; r is the paired row-state side branch.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/model_spark_vs.py:62-70',
    }),
    module({
      id: 'sparkvsk-message-passing',
      name: 'Four bipartite SPARK blocks',
      kind: 'merge',
      group: 'Learned trunk',
      stage: 4,
      lane: 0,
      inputShape: ['B', 'p', 'd'],
      outputShape: ['B', 'p', 'd'],
      transform: 'alternate Xᵀr/n and Xc/√p messages with gated residual MLP updates',
      activation: 'LayerNorm + GELU + tanh gate',
      formula: String.raw`m_c=X^{\top}r/n,\ c\leftarrow c+\tanh(g_c)\operatorname{MLP}^{\mathrm{GELU}}_c([\operatorname{LN}c;\operatorname{LN}m_c;\operatorname{pool}(c);g])`,
      explanation:
        'The default L=4 blocks repeatedly exchange information between feature coordinates and observations. The approximate 2.39M checkpoint total is displayed here as an aggregate because its exact per-module allocation was not loaded.',
      parameterCount: 2_390_000,
      repeat: { count: 4, label: 'SPARK block' },
      codeReference:
        'TROPIC_PORTABLE_20260822/model_spark.py:55-89; TROPIC_PORTABLE_20260822/model_spark_vs.py:71-73',
    }),
    module({
      id: 'sparkvsk-lambda-query',
      name: 'Penalty + λ query encoder',
      kind: 'linear',
      group: 'Conditional injection',
      stage: 5,
      lane: 0,
      inputShape: ['B', 'p', 'd'],
      outputShape: ['B', 'Q', 'q_dim'],
      transform: 'PenaltyEncoder(ρ′) then q_emb over penalty code and four λ/scale features',
      activation: 'GELU',
      formula: String.raw`\lambda_q=r_q\lambda_{\max},\quad q_q=\operatorname{MLP}^{\mathrm{GELU}}_q([\operatorname{PenEnc}(\rho');\log r_q;\tfrac15\log\lambda_q;\log s_y;\tfrac15\log\lambda_{\max}])`,
      explanation:
        'This is the exact answer to where λ enters SPARKVSK: each λ ratio is converted to λ, concatenated with the encoded penalty and scale terms, and embedded as a q_dim=32 conditional query.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/model_spark_vs.py:29-37, 167-176',
    }),
    module({
      id: 'sparkvsk-query-fusion',
      name: 'Per-(λ, coordinate) feature fusion',
      kind: 'merge',
      group: 'Conditional injection',
      stage: 6,
      lane: 0,
      inputShape: ['B', 'Q', 'q_dim'],
      outputShape: ['B', 'Q', 'p', 'F_h'],
      transform:
        'broadcast q across p and concatenate trunk, pooled, global, local-scale and optional K-features',
      activation: null,
      formula: String.raw`h_{qj}=[c_j;\operatorname{pool}(c);g;cfeat_j;\log s_{X,j};q_q;kfeat_{qj}]`,
      explanation:
        'Every λ query is injected into every coordinate. Optional query message passing and K-features add richer λ-specific coordinate evidence when enabled by the checkpoint config.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/model_spark_vs.py:177-202',
    }),
    module({
      id: 'sparkvsk-correction-head',
      name: 'Three-layer diagonal correction head',
      kind: 'linear',
      group: 'Learned path head',
      stage: 7,
      lane: 0,
      inputShape: ['B', 'Q', 'p', 'F_h'],
      outputShape: ['B', 'Q', 'p'],
      transform: 'head_vs MLP(Fh → 192 → 192 → 1) independently at each (q, j)',
      activation: 'GELU between Linear layers',
      formula: String.raw`\delta_{qj}=W_3\operatorname{GELU}(W_2\operatorname{GELU}(W_1h_{qj}+b_1)+b_2)+b_3`,
      explanation:
        'Produces the learned correction δ for each λ-coordinate pair. A configured low-rank joint head may add or replace this correction.',
      parameterCount: 0,
      repeat: { count: 3, label: 'Linear layer' },
      codeReference: 'TROPIC_PORTABLE_20260822/model_spark_vs.py:40-60, 203-218',
    }),
    module({
      id: 'sparkvsk-lqa-merge',
      name: 'LQA base scale + learned correction',
      kind: 'merge',
      group: 'Diagonal scale',
      stage: 8,
      lane: 0,
      inputShape: ['B', 'Q', 'p'],
      outputShape: ['B', 'Q', 'p'],
      transform:
        'derive base_log_d from marginal threshold and penalty slope, then add δ on non-quadratic penalties',
      activation: null,
      formula: String.raw`\log d^{base}_{qj}=\log m_{qj}-\log(\lambda^{std}_q\rho'(|\beta|)),\quad \log d_{qj}=\log d^{base}_{qj}+(1-I_{quad})\delta_{qj}`,
      explanation:
        'The neural network does not directly emit β. It adjusts a penalty-aware diagonal scale that will parameterize the following linear solve.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/model_spark_vs.py:190-219',
    }),
    module({
      id: 'sparkvsk-scale-clamp',
      name: 'Stable diagonal scale D',
      kind: 'activation',
      group: 'Diagonal scale',
      stage: 9,
      lane: 0,
      inputShape: ['B', 'Q', 'p'],
      outputShape: ['B', 'Q', 'p'],
      transform: 'clamp log_d to [ld_min, ld_max] and exponentiate inside the solver',
      activation: 'clamp then exp',
      formula: String.raw`D_q=\operatorname{diag}(\exp(\operatorname{clamp}(\log d_q,-30,8)))`,
      explanation:
        'Bounds the learned scale before the implicit solve, preventing extreme diagonal values from destabilizing PCG.',
      parameterCount: 0,
      codeReference:
        'TROPIC_PORTABLE_20260822/model_spark_vs.py:219-220; TROPIC_PORTABLE_20260822/model_spark_vs_k.py:109-114',
    }),
    module({
      id: 'sparkvsk-ipcg',
      name: 'Implicit PCG coefficient solve',
      kind: 'linear',
      group: 'Differentiable solver',
      stage: 10,
      lane: 0,
      inputShape: ['B', 'Q', 'p'],
      outputShape: ['B', 'Q', 'p'],
      transform: 'vs_solve_ipcg with K=48 default iterations; avoids explicit p × p construction',
      activation: null,
      formula: String.raw`\beta^{std}_q=D_qX^{\top}(XD_qX^{\top}+nI)^{-1}y`,
      explanation:
        'Solves the diagonal-prior regression system through the custom implicit Krylov routine. The source audit calls backward on this standalone path, but no numeric trace was captured here.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/model_spark_vs_k.py:109-114',
    }),
    module({
      id: 'sparkvsk-mm-refinement',
      name: 'Optional MM refinement',
      kind: 'linear',
      group: 'Path refinement',
      stage: 11,
      lane: 0,
      inputShape: ['B', 'Q', 'p'],
      outputShape: ['B', 'Q', 'p'],
      transform: 'recompute local penalty slopes from |β| and resolve for mm_iters iterations',
      activation: null,
      formula: String.raw`\log d^{(t+1)}_{qj}=\log|\beta^{(t)}_{qj}|-\log(\lambda^{std}_q\rho'(|\beta^{(t)}_{qj}|))`,
      explanation:
        'When mm_iters is positive, the path is iteratively reweighted and solved again. The default config shown in the source uses zero MM iterations.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/model_spark_vs.py:221-229',
    }),
    module({
      id: 'sparkvsk-output',
      name: 'Warm coefficient path βᴿ',
      kind: 'output',
      group: 'Output',
      stage: 12,
      lane: 0,
      inputShape: ['B', 'Q', 'p'],
      outputShape: ['B', 'Q', 'p'],
      transform: 'restore original response/feature units and return one coefficient vector per λ',
      activation: null,
      formula: String.raw`\beta^{R}_{bqj}=\beta^{std}_{bqj}\,s_{y,b}/s_{X,bj}`,
      explanation:
        'Returns the Q warm-start coefficient vectors consumed by the TROPIC candidate compiler. In run_tropic.py this call is evaluated in chunks under torch.no_grad().',
      parameterCount: 0,
      codeReference:
        'TROPIC_PORTABLE_20260822/model_spark_vs.py:230-234; TROPIC_PORTABLE_20260822/run_tropic.py:61-71',
    }),
  ],
  connections: [
    structuralConnection({
      id: 'sparkvsk-e-task-standardize',
      source: 'sparkvsk-task',
      target: 'sparkvsk-standardize',
      tensorName: 'X',
      shape: ['B', 'n', 'p'],
    }),
    structuralConnection({
      id: 'sparkvsk-e-standardize-krylov',
      source: 'sparkvsk-standardize',
      target: 'sparkvsk-krylov-features',
      tensorName: 'Xstd',
      shape: ['B', 'n', 'p'],
    }),
    structuralConnection({
      id: 'sparkvsk-e-krylov-embeddings',
      source: 'sparkvsk-krylov-features',
      target: 'sparkvsk-embeddings',
      tensorName: 'cfeat',
      shape: ['B', 'p', 'F_c'],
    }),
    structuralConnection({
      id: 'sparkvsk-e-embeddings-blocks',
      source: 'sparkvsk-embeddings',
      target: 'sparkvsk-message-passing',
      tensorName: 'c, r side state',
      shape: ['B', 'p', 'd'],
    }),
    structuralConnection({
      id: 'sparkvsk-e-blocks-query',
      source: 'sparkvsk-message-passing',
      target: 'sparkvsk-lambda-query',
      tensorName: 'c + pooled trunk',
      shape: ['B', 'p', 'd'],
    }),
    structuralConnection({
      id: 'sparkvsk-e-query-fusion',
      source: 'sparkvsk-lambda-query',
      target: 'sparkvsk-query-fusion',
      tensorName: 'q(λ,ρ′)',
      shape: ['B', 'Q', 'q_dim'],
    }),
    structuralConnection({
      id: 'sparkvsk-e-fusion-head',
      source: 'sparkvsk-query-fusion',
      target: 'sparkvsk-correction-head',
      tensorName: 'h(q,j)',
      shape: ['B', 'Q', 'p', 'F_h'],
    }),
    structuralConnection({
      id: 'sparkvsk-e-head-lqa',
      source: 'sparkvsk-correction-head',
      target: 'sparkvsk-lqa-merge',
      tensorName: 'δlog d',
      shape: ['B', 'Q', 'p'],
    }),
    structuralConnection({
      id: 'sparkvsk-e-lqa-clamp',
      source: 'sparkvsk-lqa-merge',
      target: 'sparkvsk-scale-clamp',
      tensorName: 'log d',
      shape: ['B', 'Q', 'p'],
    }),
    structuralConnection({
      id: 'sparkvsk-e-clamp-ipcg',
      source: 'sparkvsk-scale-clamp',
      target: 'sparkvsk-ipcg',
      tensorName: 'D',
      shape: ['B', 'Q', 'p'],
    }),
    structuralConnection({
      id: 'sparkvsk-e-ipcg-mm',
      source: 'sparkvsk-ipcg',
      target: 'sparkvsk-mm-refinement',
      tensorName: 'βstd',
      shape: ['B', 'Q', 'p'],
    }),
    structuralConnection({
      id: 'sparkvsk-e-mm-output',
      source: 'sparkvsk-mm-refinement',
      target: 'sparkvsk-output',
      tensorName: 'βstd refined',
      shape: ['B', 'Q', 'p'],
    }),
  ],
  gradientEvidence: null,
};

export const tropicLambdaPathCompiler: ModelSpec = {
  schemaVersion: 1,
  id: 'tropic-lambda-path-compiler-20260822',
  name: 'TROPIC λ-path compiler',
  version: '2026-08-22 · static source reconstruction',
  framework: 'PyTorch',
  sourceLabel: 'attached portable Python bundle · statically inspected, not executed',
  sourceArtifacts: [
    { path: 'TROPIC_PORTABLE_20260822/run_tropic.py', verified: true },
    { path: 'TROPIC_PORTABLE_20260822/model_spark.py', verified: true },
    { path: 'TROPIC_PORTABLE_20260822/tropic.py', verified: true },
    { path: 'TROPIC_PORTABLE_20260822/model_spark_vs.py', verified: true },
    { path: 'TROPIC_PORTABLE_20260822/model_spark_vs_k.py', verified: true },
    { path: 'TROPIC_PORTABLE_20260822/README.md', verified: true },
  ],
  summary:
    'A hybrid λ-path system: one learned SPARKVSK warm-path forward pass feeds a deterministic candidate substrate, active-set lattice, dynamic-programming decoder, and certification audit.',
  intent: {
    statement:
      'Compile a coherent regularization path β(λ) from a warm neural coefficient path while avoiding a full p × p solve.',
    invariants: [
      'The runner evaluates SPARKVSK once under torch.no_grad() and passes βᴿ ∈ ℝ^{Q×p} into TROPIC.',
      'Candidate restriction is capped at K ≤ 1,024 before restricted Gram and active-set solves.',
      'Every lattice state is scored by objective and active/inactive KKT residuals.',
      'Viterbi decoding couples adjacent λ layers; the final audit jointly ranks objective, continuity, and feasibility.',
      'The final coefficient path is scattered back to the original p coordinates.',
    ],
    expectedInput: ['n', 'p'],
    expectedOutput: ['Q', 'p'],
  },
  modules: [
    module({
      id: 'tropic-task',
      name: 'Regression task + penalty path',
      kind: 'input',
      group: 'Inputs',
      stage: 0,
      lane: 0,
      inputShape: ['n', 'p'],
      outputShape: ['n', 'p'],
      transform: 'center X and y; bind λ₁:Q, ratios, penalty derivative ρ′ and grid',
      activation: null,
      formula: String.raw`\mathcal{T}=\left(X\in\mathbb{R}^{n\times p},y\in\mathbb{R}^{n},\lambda_{1:Q},\rho',\mathcal{G}\right)`,
      explanation:
        'The displayed tensor contract follows the dominant design matrix X. y, λ ratios, penalty derivative, and grid are side inputs carried by the task bundle.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/run_tropic.py:38-58',
    }),
    module({
      id: 'tropic-spark-warm-path',
      name: 'SPARKVSK learned warm path',
      kind: 'linear',
      group: 'Learned front-end',
      stage: 1,
      lane: 0,
      inputShape: ['n', 'p'],
      outputShape: ['Q', 'p'],
      transform:
        'SPARKVSK.path in Q-chunks: Krylov ridge features → bipartite message passing → penalty/query head → implicit PCG',
      activation: 'GELU inside MLPs',
      formula: String.raw`\beta^{R}_{q}=\operatorname{SPARKVSK}_{\mathrm{GELU\text{-}MLP}}\!\left(X,y,\lambda_q/\lambda_{\max},\rho'\right)`,
      explanation:
        'An aggregate view of the checkpoint-backed neural front-end. The attached README declares approximately 2.39M checkpoint parameters; the checkpoint was not deserialized for this visualization.',
      parameterCount: 2_390_000,
      codeReference: 'TROPIC_PORTABLE_20260822/run_tropic.py:61-71',
      subgraph: { modelId: sparkvskLearnedWarmPath.id },
    }),
    module({
      id: 'tropic-substrate',
      name: 'GK / ISIS / KCEP substrate',
      kind: 'linear',
      group: 'Candidate reduction',
      stage: 2,
      lane: 0,
      inputShape: ['Q', 'p'],
      outputShape: ['K'],
      transform: 'block GK features + ISIS + warm-path amplitude + KCEP residual/novelty strata',
      activation: 'tanh message updates in KCEP',
      formula: String.raw`C=\operatorname{KCEP}_{\tanh}\!\left(\operatorname{cand}(X,y,\beta^{R}),\;K\le 1024\right)`,
      explanation:
        'Builds a bounded coordinate set from global/coordinate features, iterative sure-independence screening, the warm path, conditional residual scores, and novelty.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/tropic.py:89-103',
    }),
    module({
      id: 'tropic-restricted-stats',
      name: 'Restricted normal equations',
      kind: 'linear',
      group: 'Restricted problem',
      stage: 3,
      lane: 0,
      inputShape: ['K'],
      outputShape: ['K', 'K'],
      transform: 'gather X[:, C] and form restricted Gram G plus score c',
      activation: null,
      formula: String.raw`G=\frac{X_C^{\top}X_C}{n},\qquad c=\frac{X_C^{\top}y}{n}`,
      explanation:
        'All subsequent dense solves occur on the selected coordinates C rather than the full p-dimensional system.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/tropic.py:542-555',
    }),
    module({
      id: 'tropic-seeds',
      name: 'PATHC + warm-chain seeds',
      kind: 'linear',
      group: 'Lattice initialization',
      stage: 4,
      lane: 0,
      inputShape: ['K', 'K'],
      outputShape: ['Q', 'S', 'K'],
      transform:
        'seed supports from βᴿ magnitudes, marginal KKT screen, PATHC faces and previous-λ chain',
      activation: null,
      formula: String.raw`\mathcal{S}_{q}=\operatorname{Seed}\!\left(\beta^{R}_{q,C},c,\lambda_q,\rho',\mathcal{S}_{q-1}\right)`,
      explanation:
        'Initializes many support/sign/penalty-segment faces for each λ layer and carries strong states along the path.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/tropic.py:237-284',
    }),
    module({
      id: 'tropic-lattice',
      name: 'Bucketed active-set lattice',
      kind: 'linear',
      group: 'Candidate solver',
      stage: 5,
      lane: 0,
      inputShape: ['Q', 'S', 'K'],
      outputShape: ['Q', 'L', 'K'],
      transform:
        'bucket supports by size; Cholesky/LU face solve; objective + active/inactive KKT closure',
      activation: null,
      formula: String.raw`\beta_{S,h}=\left(G_{SS}+\lambda\operatorname{diag}(b_h)+\epsilon\bar g I\right)^{-1}\!\left(c_S-\lambda a_h\odot s\right)`,
      explanation:
        'Solves many local penalty faces in batches, records objective and KKT feasibility, then adds violating coordinates and repeats for the configured depth.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/tropic.py:257-321',
    }),
    module({
      id: 'tropic-expand',
      name: 'Full-p KKT expansion',
      kind: 'linear',
      group: 'Candidate expansion',
      stage: 6,
      lane: 0,
      inputShape: ['Q', 'L', 'K'],
      outputShape: ['Q', 'L', "K'"],
      transform: 'score omitted coordinates by KKT violation; add top coordinates; rerun lattice',
      activation: null,
      formula: String.raw`v_j=\max_q\frac{\left|x_j^{\top}(y-X_C\beta_q)/n\right|-\lambda_q\rho'(0)}{\lambda_q\rho'(0)}`,
      explanation:
        'Optionally reopens the restricted problem to the most violated omitted coordinates and carries the best earlier states into a second lattice pass.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/tropic.py:601-648',
    }),
    module({
      id: 'tropic-nodes',
      name: 'Representative λ-layer nodes',
      kind: 'linear',
      group: 'Path graph',
      stage: 7,
      lane: 0,
      inputShape: ['Q', 'L', "K'"],
      outputShape: ['Q', 'L_n', "K'"],
      transform: 'retain low-objective states plus support-size strata, capped by L_nodes',
      activation: null,
      formula: String.raw`\mathcal{N}_q=\operatorname{Top}_{L_n}\!\left\{\beta:F(\beta),\;|\operatorname{supp}(\beta)|\right\}`,
      explanation:
        'Compresses each λ lattice into representative states without keeping every active-set candidate.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/tropic.py:356-395',
    }),
    module({
      id: 'tropic-channels',
      name: 'Node + transition channels',
      kind: 'linear',
      group: 'Path graph',
      stage: 8,
      lane: 0,
      inputShape: ['Q', 'L_n', "K'"],
      outputShape: ['Q', 'L_n', 'L_n', 9],
      transform: '4 node costs + 5 adjacent-λ transition costs',
      activation: null,
      formula: String.raw`\phi_q=\left(\Delta F,k_i,k_a,\mathbf{1}_{\neg SPD}\right),\quad \psi_q=\left(\Delta_{cont},\Delta_{add},\Delta_{drop},\Delta_2,\Delta_{prox}\right)`,
      explanation:
        'Scores local quality and cross-λ continuity, including support changes, tangent displacement, and an exact-prox target when available.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/tropic.py:397-440',
    }),
    module({
      id: 'tropic-viterbi',
      name: 'Perturbed Viterbi hypotheses',
      kind: 'linear',
      group: 'Dynamic programming',
      stage: 9,
      lane: 0,
      inputShape: ['Q', 'L_n', 'L_n', 9],
      outputShape: ['H', 'Q'],
      transform: 'dynamic programming under deterministic channel-weight perturbations',
      activation: 'argmin',
      formula: String.raw`J_q(j)=\phi_q(j)+\min_i\left[J_{q-1}(i)+\psi_q(i,j)\right]`,
      explanation:
        'Decodes up to n_hyp unique state sequences across λ using fixed perturbations seeded by the TROPIC configuration.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/tropic.py:442-491',
    }),
    module({
      id: 'tropic-audit',
      name: 'Objective / continuity / KKT audit',
      kind: 'objective',
      group: 'Certification',
      stage: 10,
      lane: 0,
      inputShape: ['H', 'Q'],
      outputShape: ['Q', "K'"],
      transform: 'lexicographically rank objective bucket, midpoint continuity and feasibility',
      activation: 'argmin',
      formula: String.raw`p^*=\arg\min_p\left(\operatorname{round}\!\frac{\bar F_p}{\tau},\;w_c\,\operatorname{Cont}_p+w_f\,\operatorname{KKT}_p,\;\bar F_p\right)`,
      explanation:
        'The selected path is not simply the lowest local objective: it must also remain continuous and feasible across λ.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/tropic.py:493-516',
    }),
    module({
      id: 'tropic-scatter',
      name: 'Scatter to full coordinates',
      kind: 'linear',
      group: 'Reconstruction',
      stage: 11,
      lane: 0,
      inputShape: ['Q', "K'"],
      outputShape: ['Q', 'p'],
      transform: 'place selected restricted coefficients at C and keep zeros elsewhere',
      activation: null,
      formula: String.raw`\beta^{out}_{q,C}=\beta^*_{q},\qquad \beta^{out}_{q,C^c}=0`,
      explanation:
        'Restores the audited restricted path to the original feature coordinates. λ values below the compiled band retain the warm path.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/tropic.py:665-715',
    }),
    module({
      id: 'tropic-output',
      name: 'Compiled coefficient path',
      kind: 'output',
      group: 'Output',
      stage: 12,
      lane: 0,
      inputShape: ['Q', 'p'],
      outputShape: ['Q', 'p'],
      transform: 'return β_out, optionally with compiler diagnostics',
      activation: null,
      formula: String.raw`\widehat\beta(\lambda_{1:Q})=\beta^{out}\in\mathbb{R}^{Q\times p}`,
      explanation:
        'The returned regularization path is the audited TROPIC result; quadratic penalties may take the explicit warm-path passthrough branch.',
      parameterCount: 0,
      codeReference: 'TROPIC_PORTABLE_20260822/tropic.py:518-532',
    }),
  ],
  connections: [
    compilerConnection({
      id: 'tropic-e-task-warm',
      source: 'tropic-task',
      target: 'tropic-spark-warm-path',
      tensorName: 'X',
      shape: ['n', 'p'],
    }),
    compilerConnection({
      id: 'tropic-e-warm-substrate',
      source: 'tropic-spark-warm-path',
      target: 'tropic-substrate',
      tensorName: 'βᴿ',
      shape: ['Q', 'p'],
    }),
    compilerConnection({
      id: 'tropic-e-substrate-stats',
      source: 'tropic-substrate',
      target: 'tropic-restricted-stats',
      tensorName: 'C',
      shape: ['K'],
    }),
    compilerConnection({
      id: 'tropic-e-stats-seeds',
      source: 'tropic-restricted-stats',
      target: 'tropic-seeds',
      tensorName: 'G, c',
      shape: ['K', 'K'],
    }),
    compilerConnection({
      id: 'tropic-e-seeds-lattice',
      source: 'tropic-seeds',
      target: 'tropic-lattice',
      tensorName: 'seed faces',
      shape: ['Q', 'S', 'K'],
    }),
    compilerConnection({
      id: 'tropic-e-lattice-expand',
      source: 'tropic-lattice',
      target: 'tropic-expand',
      tensorName: 'lattice states',
      shape: ['Q', 'L', 'K'],
    }),
    compilerConnection({
      id: 'tropic-e-expand-nodes',
      source: 'tropic-expand',
      target: 'tropic-nodes',
      tensorName: 'expanded states',
      shape: ['Q', 'L', "K'"],
    }),
    compilerConnection({
      id: 'tropic-e-nodes-channels',
      source: 'tropic-nodes',
      target: 'tropic-channels',
      tensorName: 'layer nodes',
      shape: ['Q', 'L_n', "K'"],
    }),
    compilerConnection({
      id: 'tropic-e-channels-viterbi',
      source: 'tropic-channels',
      target: 'tropic-viterbi',
      tensorName: 'channel costs',
      shape: ['Q', 'L_n', 'L_n', 9],
    }),
    compilerConnection({
      id: 'tropic-e-viterbi-audit',
      source: 'tropic-viterbi',
      target: 'tropic-audit',
      tensorName: 'path hypotheses',
      shape: ['H', 'Q'],
    }),
    compilerConnection({
      id: 'tropic-e-audit-scatter',
      source: 'tropic-audit',
      target: 'tropic-scatter',
      tensorName: 'audited restricted path',
      shape: ['Q', "K'"],
    }),
    compilerConnection({
      id: 'tropic-e-scatter-output',
      source: 'tropic-scatter',
      target: 'tropic-output',
      tensorName: 'β_out',
      shape: ['Q', 'p'],
    }),
  ],
  gradientEvidence: null,
};

const filmTransformerBlock = {
  id: 'film-transformer-block',
  label: 'FiLM-conditioned Transformer block',
  repeatCount: 'L',
} as const;

export const filmTransformerClassifier: ModelSpec = {
  schemaVersion: 1,
  id: 'film-transformer-classifier-v1',
  name: 'FiLM-conditioned Transformer',
  version: 'v1 · executable PyTorch fixture',
  framework: 'PyTorch',
  sourceLabel: 'generator source + generated PyTorch autograd trace',
  sourceArtifacts: [{ path: 'tools/generate_residual_trace.py', verified: true }],
  summary:
    'A 4-head Transformer block whose feed-forward features are modulated by condition-derived γ and β before the second residual add.',
  intent: {
    statement:
      'Keep the token path trainable while injecting a 16-dimensional condition through explicit FiLM scale and shift tensors.',
    invariants: [
      'The attention width satisfies H × Dₕ = 4 × 16 = D = 64.',
      'Token, attention, feed-forward, γ, and β tensors all have shape [B × T × 64] at FiLM injection.',
      'FiLM applies y = (1 + γ) ⊙ x + β before the second residual addition.',
      'Both the main hidden-state path and condition encoder receive finite non-zero gradients.',
    ],
    expectedInput: ['B', 'T'],
    expectedOutput: ['B', 6],
  },
  modules: [
    module({
      id: 'tf-token-input',
      name: 'Token ids',
      kind: 'input',
      group: 'Token path',
      stage: 0,
      lane: 0,
      inputShape: ['B', 'T'],
      outputShape: ['B', 'T'],
      transform: 'integer token ids · vocabulary 128',
      activation: null,
      formula: String.raw`t \in \{0,\ldots,127\}^{B\times T}`,
      explanation: 'Discrete token indices; gradients begin at the embedding weights, not the ids.',
      parameterCount: 0,
      codeReference: 'tools/generate_residual_trace.py:148',
    }),
    module({
      id: 'tf-condition-input',
      name: 'Condition vector',
      kind: 'input',
      group: 'Condition path',
      stage: 0,
      lane: 3,
      inputShape: ['B', 16],
      outputShape: ['B', 16],
      transform: 'continuous conditioning features',
      activation: null,
      formula: String.raw`c \in \mathbb{R}^{B\times 16}`,
      explanation: 'External metadata or control features used only by the FiLM branch.',
      parameterCount: 0,
      codeReference: 'tools/generate_residual_trace.py:148',
    }),
    module({
      id: 'tf-embedding',
      name: 'Token embedding',
      kind: 'linear',
      group: 'Token path',
      stage: 1,
      lane: 0,
      inputShape: ['B', 'T'],
      outputShape: ['B', 'T', 64],
      transform: 'Embedding(128, 64)',
      activation: null,
      formula: 'h_e = E[t]',
      explanation: 'Maps each token id to the shared Transformer width D = 64.',
      parameterCount: 8_192,
      codeReference: 'tools/generate_residual_trace.py:136',
    }),
    module({
      id: 'tf-condition-encoder',
      name: 'Condition encoder',
      kind: 'linear',
      group: 'Condition path',
      stage: 1,
      lane: 3,
      inputShape: ['B', 16],
      outputShape: ['B', 32],
      transform: 'Linear(16, 32)',
      activation: 'SiLU',
      formula: String.raw`u = \operatorname{SiLU}(cW_c+b_c)`,
      explanation: 'Encodes the external condition before independent scale and shift projections.',
      parameterCount: 544,
      codeReference: 'tools/generate_residual_trace.py:142',
    }),
    module({
      id: 'tf-attention',
      name: 'Self-attention',
      kind: 'linear',
      group: 'Attention path',
      stage: 2,
      lane: -0.7,
      inputShape: ['B', 'T', 64],
      outputShape: ['B', 'T', 64],
      transform: 'MultiheadAttention(D=64, H=4, Dₕ=16)',
      activation: 'Scaled dot-product softmax',
      formula: String.raw`a=\operatorname{Concat}_{h=1}^{4}\!\left(\operatorname{softmax}\!\frac{Q_hK_h^\top}{\sqrt{16}}V_h\right)W_O`,
      explanation: 'Four 16-dimensional heads preserve the 64-dimensional hidden width.',
      parameterCount: 16_640,
      block: filmTransformerBlock,
      codeReference: 'tools/generate_residual_trace.py:137',
    }),
    module({
      id: 'tf-attention-skip',
      name: 'Attention skip',
      kind: 'linear',
      group: 'First residual',
      stage: 2,
      lane: 0.8,
      inputShape: ['B', 'T', 64],
      outputShape: ['B', 'T', 64],
      transform: 'identity',
      activation: null,
      formula: 's_a=h_e',
      explanation: 'Preserves a direct gradient path around self-attention.',
      parameterCount: 0,
      block: filmTransformerBlock,
      codeReference: 'tools/generate_residual_trace.py:151',
    }),
    module({
      id: 'tf-gamma',
      name: 'γ projection + broadcast',
      kind: 'linear',
      group: 'Condition path · scale',
      stage: 2,
      lane: 2.3,
      inputShape: ['B', 32],
      outputShape: ['B', 'T', 64],
      transform: 'Linear(32, 64) → unsqueeze → expand T',
      activation: null,
      formula: String.raw`\gamma=\operatorname{repeat}_{T}(uW_\gamma+b_\gamma)`,
      explanation:
        'Produces one feature-wise scale vector per example and broadcasts it over tokens.',
      parameterCount: 2_112,
      block: filmTransformerBlock,
      codeReference: 'tools/generate_residual_trace.py:143',
    }),
    module({
      id: 'tf-beta',
      name: 'β projection + broadcast',
      kind: 'linear',
      group: 'Condition path · shift',
      stage: 2,
      lane: 3.7,
      inputShape: ['B', 32],
      outputShape: ['B', 'T', 64],
      transform: 'Linear(32, 64) → unsqueeze → expand T',
      activation: null,
      formula: String.raw`\beta=\operatorname{repeat}_{T}(uW_\beta+b_\beta)`,
      explanation:
        'Produces one feature-wise shift vector per example and broadcasts it over tokens.',
      parameterCount: 2_112,
      block: filmTransformerBlock,
      codeReference: 'tools/generate_residual_trace.py:144',
    }),
    module({
      id: 'tf-attention-add',
      name: 'Attention residual add',
      kind: 'merge',
      group: 'First residual',
      stage: 3,
      lane: 0,
      inputShape: ['B', 'T', 64],
      outputShape: ['B', 'T', 64],
      transform: 'elementwise add',
      activation: null,
      formula: 'h_a=s_a+a',
      explanation: 'Merges the attention update with its identity path.',
      parameterCount: 0,
      block: filmTransformerBlock,
      codeReference: 'tools/generate_residual_trace.py:155',
    }),
    module({
      id: 'tf-pre-norm',
      name: 'Feed-forward pre-norm',
      kind: 'normalization',
      group: 'Main hidden-state path',
      stage: 4,
      lane: -0.5,
      inputShape: ['B', 'T', 64],
      outputShape: ['B', 'T', 64],
      transform: 'LayerNorm(64)',
      activation: null,
      formula: String.raw`\tilde h=\gamma_{LN}\odot\frac{h_a-\mu}{\sqrt{\sigma^2+\epsilon}}+\beta_{LN}`,
      explanation: 'Normalizes the main hidden-state branch before the FFN.',
      parameterCount: 128,
      block: filmTransformerBlock,
      codeReference: 'tools/generate_residual_trace.py:140',
    }),
    module({
      id: 'tf-output-skip',
      name: 'Output skip',
      kind: 'linear',
      group: 'Second residual',
      stage: 5,
      lane: 0.9,
      inputShape: ['B', 'T', 64],
      outputShape: ['B', 'T', 64],
      transform: 'identity',
      activation: null,
      formula: 's_o=h_a',
      explanation:
        'Carries the unmodulated attention representation around the FFN and FiLM branch.',
      parameterCount: 0,
      block: filmTransformerBlock,
      codeReference: 'tools/generate_residual_trace.py:158',
    }),
    module({
      id: 'tf-ffn',
      name: 'Feed-forward network',
      kind: 'linear',
      group: 'Main hidden-state path',
      stage: 5,
      lane: -0.5,
      inputShape: ['B', 'T', 64],
      outputShape: ['B', 'T', 64],
      transform: 'Linear(64, 128) → Linear(128, 64)',
      activation: 'GELU',
      formula: String.raw`x=W_2\operatorname{GELU}(\tilde hW_1+b_1)+b_2`,
      explanation: 'Expands to 128 features, applies GELU, and projects back to D = 64.',
      parameterCount: 16_576,
      block: filmTransformerBlock,
      codeReference: 'tools/generate_residual_trace.py:141',
    }),
    module({
      id: 'tf-film',
      name: 'FiLM injection',
      kind: 'activation',
      group: 'Condition injection',
      stage: 6,
      lane: 0,
      inputShape: ['B', 'T', 64],
      outputShape: ['B', 'T', 64],
      transform: 'feature-wise affine modulation',
      activation: 'FiLM',
      formula: String.raw`y=(1+\gamma)\odot x+\beta`,
      explanation:
        'Combines three shape-aligned tensors: FFN features x, broadcast scale γ, and broadcast shift β.',
      parameterCount: 0,
      block: filmTransformerBlock,
      codeReference: 'tools/generate_residual_trace.py:172',
    }),
    module({
      id: 'tf-output-add',
      name: 'Conditioned residual add',
      kind: 'merge',
      group: 'Second residual',
      stage: 7,
      lane: 0,
      inputShape: ['B', 'T', 64],
      outputShape: ['B', 'T', 64],
      transform: 'elementwise add',
      activation: null,
      formula: 'h_o=s_o+y',
      explanation: 'Adds the FiLM-modulated update to the main output skip.',
      parameterCount: 0,
      block: filmTransformerBlock,
      codeReference: 'tools/generate_residual_trace.py:173',
    }),
    module({
      id: 'tf-head',
      name: 'Classifier + probe loss',
      kind: 'output',
      group: 'Prediction',
      stage: 8,
      lane: 0,
      inputShape: ['B', 'T', 64],
      outputShape: ['B', 6],
      transform: 'mean over T → Linear(64, 6)',
      activation: 'Cross-entropy only during gradient probes',
      formula: String.raw`z=\operatorname{mean}_{T}(h_o)W_o+b_o,\quad \mathcal L=\operatorname{CE}(z,\ell)`,
      explanation:
        'Produces six logits; the generated evidence uses cross-entropy as the probe objective.',
      parameterCount: 390,
      codeReference: 'tools/generate_residual_trace.py:145',
    }),
  ],
  connections: [
    observedConnection(transformerFilmGradientEvidence, {
      id: 'tf-e-token-embedding',
      source: 'tf-token-input',
      target: 'tf-embedding',
      tensorName: 'token ids',
      shape: ['B', 'T'],
      expectedToCarryGradient: false,
    }),
    observedConnection(transformerFilmGradientEvidence, {
      id: 'tf-e-embedding-attention',
      source: 'tf-embedding',
      target: 'tf-attention',
      tensorName: 'hₑ → attention',
      shape: ['B', 'T', 64],
    }),
    observedConnection(transformerFilmGradientEvidence, {
      id: 'tf-e-embedding-attn-skip',
      source: 'tf-embedding',
      target: 'tf-attention-skip',
      tensorName: 'hₑ → skip',
      shape: ['B', 'T', 64],
    }),
    observedConnection(transformerFilmGradientEvidence, {
      id: 'tf-e-attention-add',
      source: 'tf-attention',
      target: 'tf-attention-add',
      tensorName: 'a',
      shape: ['B', 'T', 64],
    }),
    observedConnection(transformerFilmGradientEvidence, {
      id: 'tf-e-attn-skip-add',
      source: 'tf-attention-skip',
      target: 'tf-attention-add',
      tensorName: 'sₐ',
      shape: ['B', 'T', 64],
    }),
    observedConnection(transformerFilmGradientEvidence, {
      id: 'tf-e-attn-add-norm',
      source: 'tf-attention-add',
      target: 'tf-pre-norm',
      tensorName: 'hₐ → norm',
      shape: ['B', 'T', 64],
    }),
    observedConnection(transformerFilmGradientEvidence, {
      id: 'tf-e-attn-add-output-skip',
      source: 'tf-attention-add',
      target: 'tf-output-skip',
      tensorName: 'hₐ → output skip',
      shape: ['B', 'T', 64],
    }),
    observedConnection(transformerFilmGradientEvidence, {
      id: 'tf-e-norm-ffn',
      source: 'tf-pre-norm',
      target: 'tf-ffn',
      tensorName: 'h̃',
      shape: ['B', 'T', 64],
    }),
    observedConnection(transformerFilmGradientEvidence, {
      id: 'tf-e-ffn-film',
      source: 'tf-ffn',
      target: 'tf-film',
      tensorName: 'x',
      shape: ['B', 'T', 64],
    }),
    observedConnection(transformerFilmGradientEvidence, {
      id: 'tf-e-condition-encoder',
      source: 'tf-condition-input',
      target: 'tf-condition-encoder',
      tensorName: 'c',
      shape: ['B', 16],
    }),
    observedConnection(transformerFilmGradientEvidence, {
      id: 'tf-e-encoder-gamma',
      source: 'tf-condition-encoder',
      target: 'tf-gamma',
      tensorName: 'u → γ',
      shape: ['B', 32],
    }),
    observedConnection(transformerFilmGradientEvidence, {
      id: 'tf-e-encoder-beta',
      source: 'tf-condition-encoder',
      target: 'tf-beta',
      tensorName: 'u → β',
      shape: ['B', 32],
    }),
    observedConnection(transformerFilmGradientEvidence, {
      id: 'tf-e-gamma-film',
      source: 'tf-gamma',
      target: 'tf-film',
      tensorName: 'γ',
      shape: ['B', 'T', 64],
    }),
    observedConnection(transformerFilmGradientEvidence, {
      id: 'tf-e-beta-film',
      source: 'tf-beta',
      target: 'tf-film',
      tensorName: 'β',
      shape: ['B', 'T', 64],
    }),
    observedConnection(transformerFilmGradientEvidence, {
      id: 'tf-e-film-output-add',
      source: 'tf-film',
      target: 'tf-output-add',
      tensorName: 'y',
      shape: ['B', 'T', 64],
    }),
    observedConnection(transformerFilmGradientEvidence, {
      id: 'tf-e-output-skip-add',
      source: 'tf-output-skip',
      target: 'tf-output-add',
      tensorName: 'sₒ',
      shape: ['B', 'T', 64],
    }),
    observedConnection(transformerFilmGradientEvidence, {
      id: 'tf-e-output-add-head',
      source: 'tf-output-add',
      target: 'tf-head',
      tensorName: 'hₒ',
      shape: ['B', 'T', 64],
    }),
  ],
  gradientEvidence: transformerFilmGradientEvidence,
};

export const residualClassifier: ModelSpec = {
  schemaVersion: 1,
  id: 'residual-classifier-v3',
  name: 'Residual tabular classifier',
  version: 'v3 · intended design',
  framework: 'PyTorch',
  sourceLabel: 'generator source + generated PyTorch autograd trace',
  sourceArtifacts: [{ path: 'tools/generate_residual_trace.py', verified: true }],
  summary: 'A pre-normalized residual MLP for 10-class prediction from 128-dimensional inputs.',
  intent: {
    statement:
      'Preserve a direct identity path while learning a two-layer residual correction before classification.',
    invariants: [
      'The residual branch preserves width 256.',
      'The skip and residual tensors have identical shapes before addition.',
      'Every trainable path receives a finite non-zero backward signal.',
    ],
    expectedInput: ['B', 128],
    expectedOutput: ['B', 10],
  },
  modules: [
    module({
      id: 'input',
      name: 'Feature batch',
      kind: 'input',
      group: 'Input',
      stage: 0,
      lane: 0,
      inputShape: ['B', 128],
      outputShape: ['B', 128],
      transform: 'identity',
      activation: null,
      formula: 'h_0 = x',
      explanation: 'A batch of standardized real-valued features.',
      parameterCount: 0,
      codeReference: 'tools/generate_residual_trace.py:100',
    }),
    module({
      id: 'projection',
      name: 'Input projection',
      kind: 'linear',
      group: 'Encoder',
      stage: 1,
      lane: 0,
      inputShape: ['B', 128],
      outputShape: ['B', 256],
      transform: 'Linear(128, 256)',
      activation: 'GELU',
      formula: String.raw`h_1 = \operatorname{GELU}(xW_p + b_p)`,
      explanation: 'Lifts input features into the residual width.',
      parameterCount: 33_024,
      codeReference: 'tools/generate_residual_trace.py:92,101',
    }),
    module({
      id: 'pre-norm',
      name: 'Pre-normalization',
      kind: 'normalization',
      group: 'Residual block',
      stage: 2,
      lane: -1,
      inputShape: ['B', 256],
      outputShape: ['B', 256],
      transform: 'LayerNorm(256)',
      activation: null,
      formula: String.raw`\tilde h = \gamma \odot \frac{h_1-\mu}{\sqrt{\sigma^2+\epsilon}}+\beta`,
      explanation: 'Normalizes each example before the residual transformation.',
      parameterCount: 512,
      codeReference: 'tools/generate_residual_trace.py:93,107',
    }),
    module({
      id: 'residual-mlp',
      name: 'Residual transform',
      kind: 'linear',
      group: 'Residual block',
      stage: 3,
      lane: -1,
      inputShape: ['B', 256],
      outputShape: ['B', 256],
      transform: 'Linear(256, 512) → Linear(512, 256)',
      activation: 'GELU',
      formula: String.raw`r = \operatorname{GELU}(\tilde hW_1+b_1)W_2+b_2`,
      explanation: 'Learns a width-preserving nonlinear correction.',
      parameterCount: 262_912,
      codeReference: 'tools/generate_residual_trace.py:94–96,108',
    }),
    module({
      id: 'skip',
      name: 'Identity skip',
      kind: 'linear',
      group: 'Residual block',
      stage: 3,
      lane: 1,
      inputShape: ['B', 256],
      outputShape: ['B', 256],
      transform: 'identity',
      activation: null,
      formula: 's = h_1',
      explanation: 'Preserves a direct forward and backward path.',
      parameterCount: 0,
      codeReference: 'tools/generate_residual_trace.py:106',
    }),
    module({
      id: 'merge',
      name: 'Residual add',
      kind: 'merge',
      group: 'Residual block',
      stage: 4,
      lane: 0,
      inputShape: ['B', 256],
      outputShape: ['B', 256],
      transform: 'elementwise add',
      activation: null,
      formula: 'h_2 = s + r',
      explanation: 'Combines the identity and learned residual paths.',
      parameterCount: 0,
      codeReference: 'tools/generate_residual_trace.py:109–112',
    }),
    module({
      id: 'head',
      name: 'Classification head',
      kind: 'output',
      group: 'Prediction',
      stage: 5,
      lane: 0,
      inputShape: ['B', 256],
      outputShape: ['B', 10],
      transform: 'Linear(256, 10)',
      activation: 'Softmax at inference',
      formula: 'z = h_2W_o+b_o',
      explanation: 'Produces one logit for each class.',
      parameterCount: 2_570,
      codeReference: 'tools/generate_residual_trace.py:97,113',
    }),
  ],
  connections: [
    observedConnection(residualGradientEvidence, {
      id: 'e-input-projection',
      source: 'input',
      target: 'projection',
      tensorName: 'x',
      shape: ['B', 128],
    }),
    observedConnection(residualGradientEvidence, {
      id: 'e-projection-norm',
      source: 'projection',
      target: 'pre-norm',
      tensorName: 'h₁',
      shape: ['B', 256],
    }),
    observedConnection(residualGradientEvidence, {
      id: 'e-norm-residual',
      source: 'pre-norm',
      target: 'residual-mlp',
      tensorName: 'h̃',
      shape: ['B', 256],
    }),
    observedConnection(residualGradientEvidence, {
      id: 'e-projection-skip',
      source: 'projection',
      target: 'skip',
      tensorName: 'identity',
      shape: ['B', 256],
    }),
    observedConnection(residualGradientEvidence, {
      id: 'e-residual-merge',
      source: 'residual-mlp',
      target: 'merge',
      tensorName: 'r',
      shape: ['B', 256],
    }),
    observedConnection(residualGradientEvidence, {
      id: 'e-skip-merge',
      source: 'skip',
      target: 'merge',
      tensorName: 's',
      shape: ['B', 256],
    }),
    observedConnection(residualGradientEvidence, {
      id: 'e-merge-head',
      source: 'merge',
      target: 'head',
      tensorName: 'h₂',
      shape: ['B', 256],
    }),
  ],
  gradientEvidence: residualGradientEvidence,
};

export const bottleneckAutoencoder: ModelSpec = {
  schemaVersion: 1,
  id: 'bottleneck-autoencoder-v1',
  name: 'Bottleneck autoencoder',
  version: 'v1 · comparison model',
  framework: 'design-only',
  sourceLabel: 'architecture brief',
  sourceArtifacts: [],
  summary: 'A compact encoder-decoder used to compare module vocabulary across model designs.',
  intent: {
    statement:
      'Compress 128 features into a 24-dimensional code and reconstruct the original vector.',
    invariants: [
      'The bottleneck has width 24.',
      'The reconstruction shape equals the input shape.',
    ],
    expectedInput: ['B', 128],
    expectedOutput: ['B', 128],
  },
  modules: [
    module({
      id: 'ae-input',
      name: 'Feature batch',
      kind: 'input',
      group: 'Input',
      stage: 0,
      lane: 0,
      inputShape: ['B', 128],
      outputShape: ['B', 128],
      transform: 'identity',
      activation: null,
      formula: 'h_0=x',
      explanation: 'Standardized feature input.',
      parameterCount: 0,
      codeReference: 'autoencoder.py:28',
    }),
    module({
      id: 'ae-encoder',
      name: 'Encoder',
      kind: 'linear',
      group: 'Encoder',
      stage: 1,
      lane: 0,
      inputShape: ['B', 128],
      outputShape: ['B', 64],
      transform: 'Linear(128, 64)',
      activation: 'SiLU',
      formula: String.raw`h_1=\operatorname{SiLU}(xW_e+b_e)`,
      explanation: 'Reduces the feature width before the bottleneck.',
      parameterCount: 8_256,
      codeReference: 'autoencoder.py:12',
    }),
    module({
      id: 'ae-code',
      name: 'Latent code',
      kind: 'linear',
      group: 'Bottleneck',
      stage: 2,
      lane: 0,
      inputShape: ['B', 64],
      outputShape: ['B', 24],
      transform: 'Linear(64, 24)',
      activation: 'tanh',
      formula: String.raw`z=\tanh(h_1W_z+b_z)`,
      explanation: 'The intended 24-dimensional compressed representation.',
      parameterCount: 1_560,
      codeReference: 'autoencoder.py:13',
    }),
    module({
      id: 'ae-decoder',
      name: 'Decoder',
      kind: 'linear',
      group: 'Decoder',
      stage: 3,
      lane: 0,
      inputShape: ['B', 24],
      outputShape: ['B', 64],
      transform: 'Linear(24, 64)',
      activation: 'SiLU',
      formula: String.raw`h_2=\operatorname{SiLU}(zW_d+b_d)`,
      explanation: 'Expands the latent code toward the reconstruction width.',
      parameterCount: 1_600,
      codeReference: 'autoencoder.py:18',
    }),
    module({
      id: 'ae-output',
      name: 'Reconstruction',
      kind: 'output',
      group: 'Output',
      stage: 4,
      lane: 0,
      inputShape: ['B', 64],
      outputShape: ['B', 128],
      transform: 'Linear(64, 128)',
      activation: null,
      formula: String.raw`\hat x=h_2W_r+b_r`,
      explanation: 'Reconstructs the original feature vector.',
      parameterCount: 8_320,
      codeReference: 'autoencoder.py:19',
    }),
  ],
  connections: [
    connection({
      id: 'ae-e1',
      source: 'ae-input',
      target: 'ae-encoder',
      tensorName: 'x',
      shape: ['B', 128],
      activationNorm: 10.2,
      gradient: [0.052, 0.044, 0.039, 0.034, 0.031],
    }),
    connection({
      id: 'ae-e2',
      source: 'ae-encoder',
      target: 'ae-code',
      tensorName: 'h₁',
      shape: ['B', 64],
      activationNorm: 5.6,
      gradient: [0.077, 0.068, 0.059, 0.052, 0.047],
    }),
    connection({
      id: 'ae-e3',
      source: 'ae-code',
      target: 'ae-decoder',
      tensorName: 'z',
      shape: ['B', 24],
      activationNorm: 2.1,
      gradient: [0.11, 0.098, 0.086, 0.075, 0.068],
    }),
    connection({
      id: 'ae-e4',
      source: 'ae-decoder',
      target: 'ae-output',
      tensorName: 'h₂',
      shape: ['B', 64],
      activationNorm: 5.2,
      gradient: [0.18, 0.162, 0.145, 0.13, 0.117],
    }),
  ],
  gradientEvidence: null,
};

const bundledSampleModels: readonly ModelSpec[] = [
  tropicLambdaPathCompiler,
  sparkvskLearnedWarmPath,
  filmTransformerClassifier,
  residualClassifier,
  bottleneckAutoencoder,
];

const bundledFormulaFindings = modelFormulaConsistencyFindings(bundledSampleModels);
if (bundledFormulaFindings.length > 0) {
  throw new Error(
    `Bundled model formula consistency failed: ${bundledFormulaFindings.join(' | ')}`,
  );
}

export const sampleModels = bundledSampleModels;
