export const LECTURE_STUDIO_IPC_CHANNELS = {
  list: 'gosu:lecture-studio:list',
  detail: 'gosu:lecture-studio:detail',
  candidates: 'gosu:lecture-studio:candidates',
  stageExternalSources: 'gosu:lecture-studio:stage-external-sources',
  removeStagedExternalSource: 'gosu:lecture-studio:remove-staged-external-source',
  discardExternalSourceSet: 'gosu:lecture-studio:discard-external-source-set',
  importOverleaf: 'gosu:lecture-studio:import-overleaf',
  create: 'gosu:lecture-studio:create',
  updateGenerationBrief: 'gosu:lecture-studio:update-generation-brief',
  generate: 'gosu:lecture-studio:generate',
  send: 'gosu:lecture-studio:send',
  cancel: 'gosu:lecture-studio:cancel',
  trash: 'gosu:lecture-studio:trash',
  restore: 'gosu:lecture-studio:restore',
  emptyTrash: 'gosu:lecture-studio:empty-trash',
  compilePdf: 'gosu:lecture-studio:compile-pdf',
  exportArtifact: 'gosu:lecture-studio:export-artifact',
  openArtifact: 'gosu:lecture-studio:open-artifact',
  revealArtifact: 'gosu:lecture-studio:reveal-artifact',
  event: 'gosu:lecture-studio:event',
} as const;
