export const BALANCED_LITERATURE_POLICY_ID = 'balanced-three-layer' as const;
export const BALANCED_LITERATURE_POLICY_VERSION = 2;

export const LITERATURE_CORE_MIN_RELEVANCE_SCORE = 0.55;
export const LITERATURE_CORE_MIN_CITATIONS = 50;
export const LITERATURE_CORE_MIN_INFLUENTIAL_CITATIONS = 10;
export const LITERATURE_CANONICAL_MIN_AGE_YEARS = 5;

export const LITERATURE_RISING_MAX_AGE_YEARS = 3;
export const LITERATURE_RISING_MIN_RELEVANCE_SCORE = 0.35;
export const LITERATURE_RISING_MIN_CITATIONS_PER_YEAR = 2;
export const LITERATURE_RISING_MIN_INFLUENTIAL_CITATIONS = 1;
