export const SSH_IPC_CHANNELS = {
  listConnections: 'gosu:ssh:list-connections',
  createConnection: 'gosu:ssh:create-connection',
  importCommand: 'gosu:ssh:import-command',
  updateConnection: 'gosu:ssh:update-connection',
  removeConnection: 'gosu:ssh:remove-connection',
  testConnection: 'gosu:ssh:test-connection',
  readResourceSnapshot: 'gosu:ssh:read-resource-snapshot',
  readProjectResourceSnapshot: 'gosu:ssh:read-project-resource-snapshot',
  listProjectResourceSnapshots: 'gosu:ssh:list-project-resource-snapshots',
  listWorkspaceGrants: 'gosu:ssh:list-workspace-grants',
  createWorkspaceGrant: 'gosu:ssh:create-workspace-grant',
  updateWorkspaceGrant: 'gosu:ssh:update-workspace-grant',
  removeWorkspaceGrant: 'gosu:ssh:remove-workspace-grant',
  resolveApproval: 'gosu:ssh:resolve-approval',
  cancelScope: 'gosu:ssh:cancel-scope',
  event: 'gosu:ssh:event',
} as const;
