export const WORKSPACE_IPC_CHANNELS = {
  snapshot: 'gosu:workspace:snapshot',
  pendingSummary: 'gosu:workspace:pending-summary',
  createProject: 'gosu:workspace:create-project',
  renameProject: 'gosu:workspace:rename-project',
  updateProjectRepository: 'gosu:workspace:update-project-repository',
  setProjectArchived: 'gosu:workspace:set-project-archived',
  trashProject: 'gosu:workspace:trash-project',
  restoreProject: 'gosu:workspace:restore-project',
  updateBoardSettings: 'gosu:workspace:update-board-settings',
  createTask: 'gosu:workspace:create-task',
  updateTask: 'gosu:workspace:update-task',
  setTaskArchived: 'gosu:workspace:set-task-archived',
  saveObjective: 'gosu:workspace:save-objective',
  lockObjective: 'gosu:workspace:lock-objective',
  startObjectiveVersion: 'gosu:workspace:start-objective-version',
} as const;
