import { readFileSync } from 'node:fs';

import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it, vi } from 'vitest';

import {
  LectureFigureLibrary,
  isAcceptedLectureFigureFile,
  isLectureFigureFileDrag,
  lectureFigureOriginLabel,
  lectureFigureUsageLabel,
  partitionLectureFigureFiles,
  type LectureFigureAssetView,
} from '../src/renderer/src/lecture-figure-library';

function file(name: string, type: string, size = 20): File {
  return { name, type, size } as File;
}

const figures: readonly LectureFigureAssetView[] = [
  {
    id: 'figure-1',
    thumbnailDataUrl: 'data:image/png;base64,iVBORw0KGgo=',
    displayName: 'bootstrap-distribution.png',
    width: 1_600,
    height: 900,
    origin: 'user',
    usedIn: ['lecture-notes', 'slides'],
    referenceCount: 2,
    altText: 'A bootstrap distribution.',
  },
  {
    id: 'figure-2',
    thumbnailDataUrl: 'data:image/png;base64,iVBORw0KGgo=',
    displayName: 'sampling-flow.png',
    width: 1_000,
    height: 1_000,
    origin: 'generated',
    usedIn: [],
  },
];

describe('LectureFigureLibrary', () => {
  it('accepts supported raster Files without reading or exposing a local path', () => {
    expect(isAcceptedLectureFigureFile(file('plot.png', 'image/png'))).toBe(true);
    expect(isAcceptedLectureFigureFile(file('scan.TIFF', 'application/octet-stream'))).toBe(true);
    expect(isAcceptedLectureFigureFile(file('figure.avif', ''))).toBe(true);
    expect(isAcceptedLectureFigureFile(file('vector.svg', 'image/svg+xml'))).toBe(false);
    expect(isAcceptedLectureFigureFile(file('fake.png', 'text/plain'))).toBe(false);
    expect(isAcceptedLectureFigureFile(file('empty.jpg', 'image/jpeg', 0))).toBe(false);

    const result = partitionLectureFigureFiles([
      file('ok.webp', 'image/webp'),
      file('empty.png', 'image/png', 0),
      file('notes.txt', 'text/plain'),
    ]);
    expect(result.accepted.map(({ name }) => name)).toEqual(['ok.webp']);
    expect(result.rejected).toEqual([
      { fileName: 'empty.png', reason: 'empty-file' },
      { fileName: 'notes.txt', reason: 'unsupported-format' },
    ]);

    const source = readFileSync(
      new URL('../src/renderer/src/lecture-figure-library.tsx', import.meta.url),
      'utf8',
    );
    expect(source).not.toMatch(/\.path\b/u);
    expect(source).not.toContain('webkitRelativePath');
  });

  it('recognizes Finder file drags but not ordinary source-text drags', () => {
    expect(isLectureFigureFileDrag(['Files', 'text/uri-list'])).toBe(true);
    expect(isLectureFigureFileDrag(['text/plain', 'text/html'])).toBe(false);
  });

  it('labels origin and usage without relying on color alone', () => {
    expect(lectureFigureOriginLabel('user')).toBe('Added by you');
    expect(lectureFigureOriginLabel('generated')).toBe('Generated by GOSU');
    expect(lectureFigureUsageLabel(figures[0]!)).toBe('Used in Notes & Slides');
    expect(lectureFigureUsageLabel(figures[1]!)).toBe('Unused');
  });

  it('renders accessible cards, picker, drop guidance, and explicit figure actions', () => {
    const html = renderToStaticMarkup(
      <LectureFigureLibrary
        idPrefix="fixture-figures"
        figures={figures}
        activeDocument="lecture-notes"
        onChooseFiles={vi.fn()}
        onDropFiles={vi.fn()}
        onPreview={vi.fn()}
        onInsert={vi.fn()}
        onRemove={vi.fn()}
      />,
    );

    expect(html).toContain('Figures (2)');
    expect(html).toContain('Drop images from Finder here');
    expect(html).toContain('aria-label="Choose lecture figure images"');
    expect(html).toContain('Finder drop zone');
    expect(html).toContain('role="list" aria-label="Lecture figures"');
    expect(html).toContain('aria-label="bootstrap-distribution.png, Used in Notes &amp; Slides"');
    expect(html).toContain('Added by you');
    expect(html).toContain('Generated by GOSU');
    expect(html).toContain('2 references');
    expect(html).toContain('aria-label="Preview bootstrap-distribution.png"');
    expect(html).toContain('aria-label="Insert bootstrap-distribution.png in Lecture notes"');
    expect(html).toContain('aria-label="Remove bootstrap-distribution.png from this Studio"');
    expect(html).toContain('role="status" aria-live="polite"');
    expect(html).not.toContain('A bootstrap distribution.');
  });

  it('shows an accessible empty and error state', () => {
    const html = renderToStaticMarkup(
      <LectureFigureLibrary
        idPrefix="empty-figures"
        figures={[]}
        activeDocument="slides"
        onChooseFiles={vi.fn()}
        onDropFiles={vi.fn()}
        onPreview={vi.fn()}
        onInsert={vi.fn()}
        onRemove={vi.fn()}
        errorMessage="The image format is not supported."
      />,
    );
    expect(html).toContain('role="alert"');
    expect(html).toContain('The image format is not supported.');
    expect(html).toContain('No figures attached yet');
    expect(html).toContain('Insertions target Slides.');
  });

  it('supports a pre-generation library without exposing a misleading Insert action', () => {
    const html = renderToStaticMarkup(
      <LectureFigureLibrary
        idPrefix="pre-generation-figures"
        figures={figures}
        activeDocument="lecture-notes"
        canInsert={false}
        onChooseFiles={vi.fn()}
        onDropFiles={vi.fn()}
        onPreview={vi.fn()}
        onRemove={vi.fn()}
      />,
    );

    expect(html).toContain('make them available for the first generation');
    expect(html).toContain('2 figures ready for the first generation.');
    expect(html).not.toContain('Insert at cursor');
    expect(html).not.toContain('aria-label="Insert ');
    expect(html).toContain('aria-label="Remove bootstrap-distribution.png from this Studio"');
  });

  it('uses a responsive card grid and a pointer-safe drag overlay', () => {
    const styles = readFileSync(
      new URL('../src/renderer/src/lecture-figure-library.css', import.meta.url),
      'utf8',
    );
    expect(styles).toMatch(
      /\.lecture-figure-library-grid\s*\{[^}]*grid-template-columns:\s*repeat\(auto-fill,/su,
    );
    expect(styles).toMatch(/@container lecture-workspace \(max-width: 700px\)/u);
    expect(styles).toMatch(/@media \(max-width: 600px\)/u);
    expect(styles).toMatch(/\.lecture-figure-drop-overlay\s*\{[^}]*pointer-events:\s*none;/su);
  });

  it('renders a modal image preview from a renderer-safe data URL', () => {
    const html = renderToStaticMarkup(
      <LectureFigureLibrary
        idPrefix="preview-figures"
        figures={figures}
        activeDocument="lecture-notes"
        onChooseFiles={vi.fn()}
        onDropFiles={vi.fn()}
        onPreview={vi.fn()}
        onInsert={vi.fn()}
        onRemove={vi.fn()}
        previewFigure={figures[0]}
        onClosePreview={vi.fn()}
      />,
    );
    expect(html).toContain('role="dialog" aria-modal="true"');
    expect(html).toContain('Figure preview');
    expect(html).toContain('data:image/png;base64,iVBORw0KGgo=');
    expect(html).toContain('alt="A bootstrap distribution."');
    expect(html).toContain('aria-label="Close preview of bootstrap-distribution.png"');
  });
});
